services:
  doktasend-app-frontend:
    image: ghcr.io/dokta-team/doktasend-app:${VERSION_TAG}
    container_name: doktasend-app-frontend
    ports:
      - "3110:3110"  
    env_file:
      - .env
    networks:
      - shared
    environment:
      - NODE_ENV=production
    restart: unless-stopped
   
networks:
  shared:
    external: true
    name: doktasend_network
