FROM node:20-alpine

WORKDIR /usr/src/apps/frontend

COPY package*.json ./

RUN npm install

COPY . .

# ---- Build-time environment variables ----
# NEXT_PUBLIC_* are needed in the bundle
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_DOKTA_SEND_ACCESS_TOKEN
ARG NEXT_PUBLIC_DOKTA_ACCESS_USER
ARG NEXT_PUBLIC_ADMIN_ACCESS_KEY
ARG API_VERSION

# Set them as ENV so Next.js build picks them up
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_DOKTA_SEND_ACCESS_TOKEN=$NEXT_PUBLIC_DOKTA_SEND_ACCESS_TOKEN
ENV NEXT_PUBLIC_DOKTA_ACCESS_USER=$NEXT_PUBLIC_DOKTA_ACCESS_USER
ENV NEXT_PUBLIC_ADMIN_ACCESS_KEY=$NEXT_PUBLIC_ADMIN_ACCESS_KEY
ENV API_VERSION=$API_VERSION

RUN npm run build

ENV NODE_ENV=production

EXPOSE 3110

CMD ["npm", "start"]